### PR TITLE
Wishlist mgmt

### PR DESCRIPTION
**Pull request by Meghana-sk**
Features added:
Wishlist:
1. Add to wishlist when heart icon clicked on products page
2. Prevent adding same card to wishlist if it already exists in wishlist
3. Remove product from wishlist
4. Move the product to cart from wishlist

Cart page:
1. Move product to wishlist

Navbar
1. Remove unnecessary categories (Men and Women) in navbar
2. Bigger cart and wishlist icon to accomodate badge
Before:
image
After:
image

### CODE REVIEW

**Review by RahullRawat — APPROVED** [review]
Functionality is working fine. Great work @Meghana-sk

**Review by Kevin-Solomon — CHANGES_REQUESTED** [review]
The functionality works as expected but on multiple clicks of the icon, it adds multiple items to the wishlist.
Also, you can add an active state for icons when they are in the wishlist.

**Comment by Meghana-sk** [comment]
> The functionality works as expected but on multiple clicks of the icon, it adds multiple items to the wishlist. Also, you can add an active state for icons when they are in the wishlist.

ok

**Review by Abhijeet43 — APPROVED** [review]
- The functionality is working fine!!!!

**Comment by AnkurChunekar** [comment]
- On Products page the like button should toggle Add/Remove product, in your case it's navigating to wishlist page.
- As suggested by @Kevin-Solomon, Same products get added on multiple clicks.
- Have an active state to like icon, maybe you change the background color to red.
- Rest everything looks good, functionality works as intended.
- great work @Meghana-sk

**Review by AnkurChunekar — APPROVED** [review]

**Pull request merged**
